backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'content: create {{collection}} "{{slug}}"'
    update: 'content: update {{collection}} "{{slug}}"'
    delete: 'content: delete {{collection}} "{{slug}}"'
    uploadMedia: 'media: upload {{path}}'
    deleteMedia: 'media: delete {{path}}'

local_backend: true

media_folder: public/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: audio-excerpts
    label: Audio Excerpts
    folder: content/audio-excerpts
    create: true
    slug: '{{slug}}'
    media_folder: /public/content/audio
    public_folder: /content/audio
    editor:
      preview: true
    fields:
      - label: Template Key
        name: templatekey
        widget: hidden
        default: audio-excerpt
      - label: Title
        name: title
        widget: string
      - label: Audio File
        name: audiofile
        widget: file
        allow_multiple: false
        media_library:
          config:
            multiple: false
      - label: Description
        name: description
        widget: text
        required: false
      - label: Published
        name: published
        widget: boolean
        default: true

  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: index
    media_folder: /public/content/blog/{{year}}/{{month}}/{{title}}
    public_folder: ''
    path: '{{year}}/{{month}}/{{title}}/index'
    editor:
      preview: true
    fields:
      - label: Template Key
        name: templatekey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
      - label: Audio Excerpt
        name: audioexcerpt
        widget: relation
        collection: audio-excerpts
        search_fields:
          - title
        value_field: '{{slug}}'
        display_fields:
          - title
        required: false
      - label: Featured Post
        name: featuredpost
        widget: boolean
        required: false
        default: false
      - label: Featured Image
        name: featuredimage
        widget: image
        required: false

  - name: pages
    label: Pages
    folder: content/pages
    create: true
    slug: '{{title}}'
    media_folder: /public/content/pages
    public_folder: /content/pages
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - label: Template Key
        name: templatekey
        widget: hidden
        default: page
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Audio Players
        name: audioplayers
        widget: list
        required: false
        fields:
          - label: Audio Excerpt
            name: excerpt
            widget: relation
            collection: audio-excerpts
            search_fields:
              - title
            value_field: '{{slug}}'
            display_fields:
              - title
      - label: Featured Image
        name: featuredimage
        widget: image
        required: false

  - name: home
    label: Home
    files:
      - file: content/home/index.md
        label: Home Page
        name: home
        editor:
          preview: true
        fields:
          - label: Template Key
            name: templatekey
            widget: hidden
            default: index-page
          - label: Title
            name: title
            widget: string
          - label: Main Navigation
            name: navigation
            widget: list
            fields:
              - label: Display Text
                name: title
                widget: string
              - label: URL Path
                name: slug
                widget: string
              - label: Show Cart Indicator
                name: showcartindicator
                widget: boolean
                required: false
                default: false
              - label: Sub Navigation Items
                name: subnav
                widget: list
                required: false
                fields:
                  - label: Display Text
                    name: title
                    widget: string
                  - label: URL Path
                    name: slug
                    widget: string
                  - label: Description
                    name: description
                    widget: text
                    required: false
          - label: Tagline
            name: tagline
            widget: string
          - label: Home Quote
            name: homequote
            widget: text
          - label: Featured Audio Excerpt
            name: featuredaudio
            widget: relation
            collection: audio-excerpts
            search_fields:
              - title
            value_field: '{{slug}}'
            display_fields:
              - title
            required: false
          - label: Featured Image
            name: featuredimage
            widget: image
            required: false
            media_folder: /public/content/home
            public_folder: /content/home
          - label: Footer Bio Image
            name: footerbioimage
            widget: image
            required: false
            media_folder: /public/content/home
            public_folder: /content/home
          - label: About Nina Footer Bio Text
            name: footerbiotext
            widget: text
          - label: Social Links
            name: sociallinks
            widget: list
            fields:
              - label: Link Name
                name: title
                widget: string
              - label: URL
                name: url
                widget: string
          - label: Meet Nina Footer Text
            name: footermeettext
            widget: text
          - label: Footer Credits
            name: footercredits
            widget: list
            fields:
              - label: Text
                name: text
                widget: string
              - label: Link Text
                name: linktext
                widget: string
              - label: URL
                name: url
                widget: string
          - label: Body
            name: body
            widget: markdown
